# Generated by Django 5.1.3 on 2024-11-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=20)),
                ('Placa', models.CharField(max_length=10)),
                ('Marca', models.CharField(max_length=20)),
            ],
        ),
    ]
