# Generated by Django 5.1.3 on 2024-11-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='Upload',
            field=models.ImageField(default=100, upload_to='cars'),
            preserve_default=False,
        ),
    ]
