# Generated by Django 5.1.3 on 2024-12-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_cadastro_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('CPF', models.CharField(max_length=11)),
                ('Endereço', models.CharField(max_length=200)),
            ],
        ),
    ]
